// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TerrariumController.Data;

#nullable disable

namespace TerrariumController.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260102203618_SeedDefaults")]
    partial class SeedDefaults
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("TerrariumController.Models.HumidityLockoutState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastTriggeredTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LockExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SensorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("HumidityLockoutStates");
                });

            modelBuilder.Entity("TerrariumController.Models.LogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LogType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RelayId")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("RelayState")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Sensor1Humidity")
                        .HasColumnType("REAL");

                    b.Property<double?>("Sensor1Temperature")
                        .HasColumnType("REAL");

                    b.Property<double?>("Sensor2Humidity")
                        .HasColumnType("REAL");

                    b.Property<double?>("Sensor2Temperature")
                        .HasColumnType("REAL");

                    b.Property<double?>("Sensor3Humidity")
                        .HasColumnType("REAL");

                    b.Property<double?>("Sensor3Temperature")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp")
                        .IsDescending();

                    b.ToTable("LogEntries");
                });

            modelBuilder.Entity("TerrariumController.Models.RelayState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("RelayId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("SensorHumidity")
                        .HasColumnType("REAL");

                    b.Property<double?>("SensorTemperature")
                        .HasColumnType("REAL");

                    b.Property<int?>("SourceSensorId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("State")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggerSource")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp")
                        .IsDescending();

                    b.ToTable("RelayStates");
                });

            modelBuilder.Entity("TerrariumController.Models.SensorReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Humidity")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsValid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.Property<int>("SensorId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Temperature")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp")
                        .IsDescending();

                    b.ToTable("SensorReadings");
                });

            modelBuilder.Entity("TerrariumController.Models.Settings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CameraFramerate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CameraHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CameraWidth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HumidityLockoutHours")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<int>("LogRetentionMonths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Relay1GPIO")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Relay2GPIO")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Relay3GPIO")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Relay4GPIO")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Relay4OffTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Relay4OnTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Relay5GPIO")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Relay6GPIO")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Sensor1HumidityThreshold")
                        .HasColumnType("REAL");

                    b.Property<double>("TemperatureHysteresis")
                        .HasColumnType("REAL");

                    b.Property<double>("Threshold1Temperature")
                        .HasColumnType("REAL");

                    b.Property<double>("Threshold2Temperature")
                        .HasColumnType("REAL");

                    b.Property<double>("Threshold3Temperature")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CameraFramerate = 15,
                            CameraHeight = 720,
                            CameraWidth = 1280,
                            HumidityLockoutHours = 6,
                            LastModified = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LogRetentionMonths = 12,
                            Relay1GPIO = 29,
                            Relay2GPIO = 31,
                            Relay3GPIO = 33,
                            Relay4GPIO = 35,
                            Relay4OffTime = "20:00",
                            Relay4OnTime = "08:00",
                            Relay5GPIO = 37,
                            Relay6GPIO = 40,
                            Sensor1HumidityThreshold = 60.0,
                            TemperatureHysteresis = 1.0,
                            Threshold1Temperature = 29.0,
                            Threshold2Temperature = 29.0,
                            Threshold3Temperature = 29.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
